<a href="https://colab.research.google.com/github/7ayush/FiveSem/blob/main/DataScience_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ayush Kaushik 101903619 Assignment 3 Data Science

In [1]:
import numpy as np

In [2]:
#Q1
arr = np.arange(10)
even = arr[np.where(arr%2==0)]
odd = arr[np.where(arr%2!=0)]
print(even)
print(odd)
arr[np.where(arr%2==0)]=0
print(arr)

[0 2 4 6 8]
[1 3 5 7 9]
[0 1 0 3 0 5 0 7 0 9]


In [3]:
#Q2
arr = np.arange(15)
index = np.where(arr%2!=0)
new = arr.astype(str)
new[index] = 'odd'
print(new)

['0' 'odd' '2' 'odd' '4' 'odd' '6' 'odd' '8' 'odd' '10' 'odd' '12' 'odd'
 '14']


In [4]:
#Q3
a = np.array(['How','Are','You'])
b = np.repeat(a,3)
c = np.tile(a,3)
print(np.append(b,c))

['How' 'How' 'How' 'Are' 'Are' 'Are' 'You' 'You' 'You' 'How' 'Are' 'You'
 'How' 'Are' 'You' 'How' 'Are' 'You']


In [5]:
#Q4
a = np.array(['a','b','c','r','g'])
b = np.array(['z','c','e','a'])
print(np.intersect1d(a,b))

['a' 'c']


In [6]:
#Q5
a = np.arange(25).reshape(5,5)
print("Original Array - ")
print(a)
a[:,[-2,-1]]=a[:,[-1,-2]]
print("\nArray after swapping last 2 columns - ")
print(a)
a[[0,1],:]=a[[1,0],:]
print("\nArray after swapping first 2 rows - ")
print(a)

Original Array - 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Array after swapping last 2 columns - 
[[ 0  1  2  4  3]
 [ 5  6  7  9  8]
 [10 11 12 14 13]
 [15 16 17 19 18]
 [20 21 22 24 23]]

Array after swapping first 2 rows - 
[[ 5  6  7  9  8]
 [ 0  1  2  4  3]
 [10 11 12 14 13]
 [15 16 17 19 18]
 [20 21 22 24 23]]


In [7]:
#Q6
a = np.array(np.random.uniform(6,12,15).reshape(5,3))
print(a)

[[ 7.47156156 11.21992448 10.68876964]
 [11.9186806   6.15430823  8.63290175]
 [ 9.39699553 10.67296696  6.50238181]
 [11.80057869 10.88850601  7.35736656]
 [ 9.87646145  6.67445443  6.83679081]]


In [8]:
#Q7
np.set_printoptions(precision=2)
a = np.random.random(size=10)
print(a)

[0.48 0.23 0.69 0.8  0.65 0.31 0.16 0.7  0.02 0.92]


In [9]:
#Q8
iris_2d = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",dtype=float,delimiter=',',usecols=[0,1,2,3])
print(iris_2d)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
#Q9
sepal_length = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",dtype=float,delimiter=',',usecols=[0])
print("Mean of Iris Sepal Length is = ",np.mean(sepal_length))
print("Median of Iris Sepal Length is = ",np.median(sepal_length))
print("Standard Deviation of Iris Sepal Length is = ",np.std(sepal_length))

Mean of Iris Sepal Length is =  5.843333333333334
Median of Iris Sepal Length is =  5.8
Standard Deviation of Iris Sepal Length is =  0.8253012917851409
